name: terraform-plan

inputs:
  aws-region:
    required: true
    type: string
  aws-account-id:
    required: true
    type: string
  terraform_role_name:
    required: true
    type: string
  terraform_version:
    required: true
    type: string
  backend_bucket:
    required: true
    type: string
  backend_key:
    required: true
    type: string
  lock_table:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/${{ inputs.terraform_role_name }}
        role-session-name: ${{ inputs.terraform_role_name }}-session

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Terraform format
      id: fmt
      run: terraform fmt -check

    - name: Terraform init
      id: init
      # setup bucket and lock table
      run: |
        terraform init \
          -backend-config="bucket=${{ inputs.backend_bucket }}" \
          -backend-config="key=${{ inputs.backend_key }}" \
          -backend-config="dynamodb_table=${{ inputs.lock_table }}"

    - name: Terraform validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan >/dev/null -no-color -out=tfplan
      continue-on-error: true

    - name: Terraform Show
      id: show
      run: terraform show tfplan -no-color

    - uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.show.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
          <details><summary>Validation Output</summary>
          \`\`\`\n
          ${{ steps.validate.outputs.stdout }}
          \`\`\`
          </details>
          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
          <details><summary>Show Plan</summary>
          \`\`\`\n
          ${process.env.PLAN}
          \`\`\`
          </details>
          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
