WATER_INTENSITY_MIN = 0
WATER_INTENSITY_MAX = 6
WATER_VULNERABILITY_MIN = 0
WATER_VULNERABILITY_MAX = 100
AAL_MIN = 0
AAL_MAX = 0.05
RISK_INDEX_MIN = 0
RISK_INDEX_MAX = 5


flood_layer_range = {
    "water_intensity_rp20": (WATER_INTENSITY_MIN, WATER_INTENSITY_MAX),
    "water_intensity_rp100": (WATER_INTENSITY_MIN, WATER_INTENSITY_MAX),
    "water_intensity_rp200": (WATER_INTENSITY_MIN, WATER_INTENSITY_MAX),
    "vulnerability_rp20": (WATER_VULNERABILITY_MIN, WATER_VULNERABILITY_MAX),
    "vulnerability_rp100": (WATER_VULNERABILITY_MIN, WATER_VULNERABILITY_MAX),
    "vulnerability_rp200": (WATER_VULNERABILITY_MIN, WATER_VULNERABILITY_MAX),
    "aal": (AAL_MIN, AAL_MAX),
    "risk_index": (RISK_INDEX_MIN, RISK_INDEX_MAX),
}
