name: Build, push and update lambda images for flood baseline and rcp 8.5, 2.6 and 4.5

on:
  push:
    paths:
      - 'src/api/flood/**'
      - 'src/api/common/**'
      - '.github/workflows/flood.yml'
      - '.github/workflows/build-test-deploy.yml'
      - '.github/actions/build-push-layout/action.yml'
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  floodbase-build-push:
    uses: ./.github/workflows/build-test-deploy.yml
    with:
      aws-role-name: gh_flood
      aws-account-id: 600920596656
      aws-region: eu-central-1
      climate-scenario: baseline
      risk-folder: flood/baseline
      image-name: apinine_flood
      lambda-name: apinine_flood

  flood26-build-push:
    uses: ./.github/workflows/build-test-deploy.yml
    with:
      aws-role-name: gh_flood
      aws-account-id: 600920596656
      aws-region: eu-central-1
      climate-scenario: rcp26
      risk-folder: flood/rcp
      image-name: apinine_flood_rcp26
      lambda-name: apinine_flood_rcp26

  flood45-build-push:
    uses: ./.github/workflows/build-test-deploy.yml
    with:
      aws-role-name: gh_flood
      aws-account-id: 600920596656
      aws-region: eu-central-1
      climate-scenario: rcp45
      risk-folder: flood/rcp
      image-name: apinine_flood_rcp45
      lambda-name: apinine_flood_rcp45

  flood85-build-push:
    uses: ./.github/workflows/build-test-deploy.yml
    with:
      aws-role-name: gh_flood
      aws-account-id: 600920596656
      aws-region: eu-central-1
      climate-scenario: rcp85
      risk-folder: flood/rcp
      image-name: apinine_flood_rcp85
      lambda-name: apinine_flood_rcp85