name: "Terraform apply"

on:
  push:
    paths:
      - "infra/**"
      - ".github/workflows/terraform_apply.yml"
    branches: ["tf_apply_workflow"] # FIXME: restore main

permissions:
  id-token: write
  contents: read
  issues: write

env:
  aws-account-id: 600920596656
  aws-region: eu-central-1
  #TF_LOG: INFO
  TF_IN_AUTOMATION: 1
  terraform_version: "1.7.4"
  terraform_role_name: github_actions_terraform_apinine
  backend_bucket: terraform-be-bucket
  backend_key: apinine/terraform.tfstate
  lock_table: terraform-be-locktable

jobs:
  tf_plan:
    permissions: write-all
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: ./infra

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.aws-region }}
          role-to-assume: arn:aws:iam::${{ env.aws-account-id }}:role/${{ env.terraform_role_name }}
          role-session-name: ${{ env.terraform_role_name }}-session

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.terraform_version }}

      - name: Terraform format
        id: fmt
        run: terraform fmt -check

      - name: Terraform init
        id: init
        # setup bucket and lock table
        run: |
          terraform init \
            -backend-config="bucket=${{ env.backend_bucket }}" \
            -backend-config="key=${{ env.backend_key }}" \
            -backend-config="dynamodb_table=${{ env.lock_table }}"

      - name: Terraform validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Show Plan
        id: show_plan
        run: terraform show -no-color tfplan

      - name: Approve Plan to Apply
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          minimum-approvals: 1
          approvers: ggrangia,fromgold,gionnid
          issue-title: "Approve Terraform Plan to be applied"
          issue-body: "Review the terraform plan, then approve or deny the deployment to prod\n\n${{ steps.show_plan.outputs.stdout }}"
          exclude-workflow-initiator-as-approver: false

      - name: Apply plan
        id: apply
        run: terraform apply -input=false tfplan
