name: "Run unit tests on PR"

on:
  pull_request:
    branches: ["main"]

env:
  aws-role-name: gh_drought
  aws-account-id: 600920596656
  aws-region: eu-central-1

jobs:
  show:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run unit tests
        run: |
          cd src
          make testall_unit

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.aws-region }}
          role-to-assume: arn:aws:iam::${{ env.aws-account-id }}:role/${{ env.aws-role-name }}
          role-session-name: ${{ env.aws-role-name }}-session


      - name: Run unit tests
        run: |
          cd src
          make testall
