name: Build, push and update lambda images for wildfire

on:
  push:
    paths:
      - 'src/api/wildfire/**'
      - 'src/api/common/**'
      - '.github/workflows/wildfire.yml'
      - '.github/workflows/build-test-deploy.yml'
      - '.github/actions/build-push-layout/action.yml'
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  wildfire-build-push:
    uses: ./.github/workflows/build-test-deploy.yml
    with:
      aws-role-name: gh_wildfire
      aws-account-id: 600920596656
      aws-region: eu-central-1
      geotiff-keyword: GEOTIFF_PATH
      risk-folder: wildfire
      image-name: apinine_wildfire_rcp85
      lambda-name: apinine_wildfire_rcp85
